---
exclude: "(frontend/src/generated/|backend/migrations/versions/)"

repos:
  - repo: local
    hooks:

      - id: check-added-large-files
        name: Check for added large files
        entry: check-added-large-files
        language: system

      - id: end-of-file-fixer
        name: Fix End of Files
        entry: end-of-file-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]

      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]

      # backend
      - id: black
        name: black
        entry: black
        language: system
        files: backend/
        types: [python]
        require_serial: true

      - id: flake8
        name: flake8
        language: system
        entry: bash -c "cd backend && exec flake8"
        files: backend/
        types: [python]
        require_serial: true

      - id: reorder-python-imports
        name: Reorder python imports
        language: system
        entry: reorder-python-imports
        files: backend/
        types: [python]
        args: [--application-directories=backend]

      - id: check-toml
        name: Check Toml
        entry: check-toml
        language: system
        files: backend/
        types: [toml]

      - id: check-yaml
        name: Check Yaml
        entry: check-yaml
        language: system
        files: backend/
        types: [yaml]

  # frontend
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
      - id: prettier
        files: frontend/
        types_or: [javascript, jsx, ts, tsx]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v7.20.0"
    hooks:
      - id: eslint
        files: frontend/
        types_or: [javascript, jsx, ts, tsx]
