---
version: "3.9"

services:
  nginx:
    profiles:
      - proxy

  postgres:
    ports:
      - 5432:5432

  pgadmin:
    ports:
      - 5050:5050

  backend:
    profiles:
      - backend

  frontend:
    build:
      context: ./frontend
      args:
        FRONTEND_ENV: dev
    profiles:
      - frontend
