---
version: "3.9"

services:
  nginx:
    profiles:
      - proxy

  postgres:
    ports:
      - 5432:5432

  pgadmin:
    ports:
      - 5050:5050

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:{{cookiecutter.backend_port}}
    volumes:
      - ./backend:/{{cookiecutter.project_slug}}:cached
    profiles:
      - backend

  frontend:
    build:
      context: ./frontend
      args:
        FRONTEND_ENV: dev
    profiles:
      - frontend
