---
version: "3.9"

services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - app-db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 2s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    command: uvicorn app.main:app --host 0.0.0.0 --port {{cookiecutter.backend_port}}
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      args:
        FRONTEND_ENV: ${FRONTEND_ENV-production}

volumes:
  app-db-data:
  pgadmin:
